# Generated by Django 4.1.3 on 2022-12-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_curso_numero_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriasFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('comision', models.IntegerField()),
                ('cantidad_dia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfesoresFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('comision', models.IntegerField()),
                ('cantidad_dia', models.IntegerField()),
            ],
        ),
    ]
