# Generated by Django 4.1.3 on 2022-12-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_materiasformulario_profesoresformulario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriasFormulario',
            new_name='Materias',
        ),
        migrations.RenameModel(
            old_name='ProfesoresFormulario',
            new_name='Profesores',
        ),
    ]
